# Generated by Django 5.0.7 on 2024-07-20 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='group_chat',
            new_name='chat_name',
        ),
    ]
