# Generated by Django 5.0.7 on 2024-07-22 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_rename_group_chat_chatroom_chat_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='user_online',
            field=models.ManyToManyField(blank=True, related_name='user_in_online', to=settings.AUTH_USER_MODEL),
        ),
    ]
