# Generated by Django 5.0.7 on 2024-07-23 08:57

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_alter_chatroom_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='image',
        ),
        migrations.AddField(
            model_name='messages',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='group_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
